name: smart_progress_circle
description: "SmartProgressCircle is a customizable Flutter widget for displaying dynamic circular progress. Ideal for real-time updates in apps like fitness trackers and dashboards."
version: 0.0.6
homepage: https://github.com/developerashkan/smart_progress_circle
repository: https://github.com/developerashkan/smart_progress_circle

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms: {}
